### PR TITLE
add test for 2D CLI

### PR DESCRIPTION
**Pull request by martinschorb**
this addresses #127 

Test fails to demonstrate the issue. WIP

### CODE REVIEW

**Comment by martinschorb** [comment]
Is it OK if we just choose `ome.zarr` as default? I guess by now, that would be my call.

Or will it break some older scripts that assume `bdv.n5` to be in there as default for all eternity?

**Comment by martinschorb** [comment]
Maybe this would then justify an increase in version number (minor only). What do you think @constantinpape ?

**Comment by constantinpape** [comment]
I agree @martinschorb. We should switch the default and then bump the minor version.

**Comment by martinschorb** [comment]
looks like there are a bunch of tests relying on the default.
Will look into it and try to fix them.

**Review by constantinpape — COMMENTED** [review]
The changes look good now. But the default data format should also be changed for other functions, e.g. https://github.com/mobie/mobie-utils-python/blob/master/mobie/segmentation.py#L20.

But we can also do this in a separate PR and merge this one now.

**Comment by martinschorb** [comment]
I found that this test is full of explicit bdv.n5 calls. https://github.com/mobie/mobie-utils-python/blob/master/test/metadata/test_source_metadata.py 

But I don't fully understand the way these tests work and if the format plays a role at all for them.

**Comment by constantinpape** [comment]
> I found that this test is full of explicit bdv.n5 calls.

The reason is that this test checks for the json validation of the source field and has some specific settings for `bdv.n5`, see
https://github.com/mobie/mobie-utils-python/blob/master/test/metadata/test_source_metadata.py#L19-L22

I think we can leave this test as it is.

**Comment by constantinpape** [comment]
I have updated the remaining places where the default file format was still `bdv.n5`. I will look into the failing tests later.

**Comment by martinschorb** [comment]
I am totally fine with some functionality being restricted to (legacy) file formats. 
For the sorresponding tests, I would just explicitely specify the format.

**Pull request merged**
